### ISSUE TITLE
hts_idx_push() doesn't handle POS=0 (leading to bcftools index segfault)

### ISSUE THREAD

**Issue by jmarshall** [samtools/htslib#406]
As [reported by Yuelin Jack Zhu on samtools-help](https://sourceforge.net/p/samtools/mailman/message/35295106/), indexing a BCF file containing records with a POS field of 0 leads to a segfault:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004c5796 in insert_to_l (l=0x79ca40, _beg=-1, _end=0, 
    offset=3578404129681, min_shift=14) at hts.c:1205
1205	        if (l->offset[beg] == (uint64_t)-1) l->offset[beg] = offset;
(gdb) bt
#0  0x00000000004c5796 in insert_to_l (l=0x79ca40, _beg=-1, _end=0, 
    offset=3578404129681, min_shift=14) at hts.c:1205
#1  0x00000000004c6725 in hts_idx_push (idx=0x799780, tid=80, beg=-1, end=0, 
    offset=3578404139953, is_mapped=1) at hts.c:1371
```

This is the first call to `insert_to_l()` for this `tid` (aka `rid`), so `l->offset` is still NULL, and with these values for `_beg`/`_end` the `realloc()` is not triggered.

For VCF/BCF such a POS value is valid (and not unmapped as SAM would consider it):

> POS […] Telomeres are indicated by using positions 0 or N+1, where N is the length of the corresponding chromosome or contig

**Comment by jmarshall** [comment]
I think the right fix for this is to consider this 1-base-at-POS=0 region to be in the nearest appropriate bin, i.e., the lowest-level (i.e. smallest) leftmost bin starting at POS=1 (0-based 0), with something like:

```diff
--- a/hts.c
+++ b/hts.c
@@ -1366,8 +1366,12 @@ int hts_idx_push(hts_idx_t *idx, int tid, int beg, int en
     if ( tid>=0 )
     {
         if (idx->bidx[tid] == 0) idx->bidx[tid] = kh_init(bin);
-        if ( is_mapped)
+        if (is_mapped) {
+            // shoehorn [-1,0) (VCF POS=0) into the leftmost bottom-level bin
+            if (beg < 0)  beg = 0;
+            if (end <= 0) end = 1;
             insert_to_l(&idx->lidx[tid], beg, end, idx->z.last_off, idx->min_sh
+        }
     }
```

This way the index will capture it as present at the start of its chromosome, beside the entries for POS=1, 2, 3, etc.

However `bcftools view foo.bcf seq` does not print the entry: it is returned by `readrec()`, but `hts_itr_next()` ignores it and reads again as it is outwith the requested `seq:1-seqlen` region.  So that's a separate bug or limitation.
