### ISSUE TITLE
A SEGV signal occurred when running program sam in test directory

### ISSUE THREAD

**Issue by fCorleone** [samtools/htslib#728]
Details are displayed as:
```
ASAN:SIGSEGV
=================================================================
==30194==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000044 (pc 0x00000047d41d bp 0x7ffd40088fa0 sp 0x7ffd40088f70 T0)
    #0 0x47d41c in sam_hdr_write /home/mfc_fuzz/htslib/sam.c:1069
    #1 0x40852a in copy_check_alignment test/sam.c:470
    #2 0x408853 in samrecord_layout test/sam.c:512
    #3 0x409043 in main test/sam.c:576
    #4 0x7fb07eb4882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #5 0x403818 in _start (/home/mfc_fuzz/htslib/test/sam+0x403818)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/mfc_fuzz/htslib/sam.c:1069 sam_hdr_write
==30194==ABORTING

```

**Comment by jkbonfield** [comment]
Thanks for the bug report.  Is this with the current develop branch?

**Comment by daviesrob** [comment]
`test/sam` on `develop` seems happy when I tried it with AddressSanitizer (gcc 8.1.0) on the usual inputs.

Did you use some other input to provoke this, and if so would it be possible to attach it here?

**Comment by daviesrob** [comment]
Aha!  Got it to go wrong by running ./sam in the test directory.
```
./sam ce.fa faidx.fa fastqs.fq[E::hts_open_format] Failed to open file test/sam_alignment.tmp.bam
Failed: writing headers to test/sam_alignment.tmp.bam
AddressSanitizer:DEADLYSIGNAL
=================================================================
==40028==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000044 (pc 0x00000044b7ae bp 0x6060000004a0 sp 0x7fff6d808b90 T0)
```

Caused by a lack of error checking in `copy_check_alignment()`.
